<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Ensou.Dsh.Personal.ClientTests" />
    <InternalsVisibleTo Include="Ensou.Dsh.Personal.Windows" />
    <InternalsVisibleTo Include="Ensou.Dsh.Personal.WindowsTests" />
    <InternalsVisibleTo Include="Ensou.Dsh.Personal.CngTests" />
  </ItemGroup>
</Project>
