<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Ensou.Dsh.Enterprise.Installation</RootNamespace>
    <AssemblyName>Ensou.Dsh.Enterprise.ReleaseContracts</AssemblyName>
    <Product>Ensou DSH Enterprise Release Contracts</Product>
  </PropertyGroup>
</Project>
